FROM bitnami/laravel:12

WORKDIR /app

COPY . /app/

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cp .env.staging .env

RUN composer install --no-dev --optimize-autoloader

RUN composer require fakerphp/faker --dev