name: Push and Run

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:
    
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php 
      - name: Run tests
        run: php artisan test

  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cs-cim:latest ./server

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cs-cim:latest

  Deploy-Laravel-Docker:
    needs: Build-Laravel-And-Push-Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/cs-cim:latest
            docker-compose up -d