name: Frontend Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - stage
      - release
jobs:
  Run-frontend-Tests:
    name: Run frontend tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' 

      - name: Install dependencies
        working-directory: birdly-client
        run: npm install

      - name: Run frontend tests
        working-directory: birdly-client
        run: npm run test -- --run